using System;
using System.Collections.Generic;
using System.Linq;
using ModelLuhy.Configuration;
using SOSIEL.Entities;
using SOSIEL.Helpers;
using SOSIEL.Randoms;

namespace ModelLuhy
{
    public sealed class Agent : SOSIEL.Entities.Agent
    {
        public AgentStateConfiguration AgentStateConfiguration { get; private set; }

        public override SOSIEL.Entities.Agent Clone()
        {
            Agent agent = (Agent)base.Clone();

            return agent;
        }

        public override SOSIEL.Entities.Agent CreateChild(string gender)
        {
            Agent child = (Agent)base.CreateChild(gender);

            child[AlgorithmVariables.AgentIncome] = 0;
            child[AlgorithmVariables.AgentExpenses] = 0;
            child[AlgorithmVariables.AgentSavings] = 0;

            return child;
        }

        protected override SOSIEL.Entities.Agent CreateInstance()
        {
            return new Agent();
        }

        public void GenerateCustomParams()
        {

        }

        /// <summary>
        /// Creates agent instance based on agent archetype and agent configuration 
        /// </summary>
        /// <param name="agentConfiguration"></param>
        /// <param name="archetype"></param>
        /// <returns></returns>
        public static Agent CreateAgent(AgentStateConfiguration agentConfiguration, AgentArchetype archetype)
        {
            Agent agent = new Agent();

            agent.Archetype = archetype;
            agent.privateVariables = new Dictionary<string, dynamic>(agentConfiguration.PrivateVariables);

            agent.AssignedDecisionOptions = archetype.DecisionOptions.Where(r => agentConfiguration.AssignedDecisionOptions.Contains(r.Id)).ToList();
            agent.AssignedGoals = archetype.Goals.Where(g => agentConfiguration.AssignedGoals.Contains(g.Name)).ToList();

            agent.AssignedDecisionOptions.ForEach(kh => agent.DecisionOptionActivationFreshness.Add(kh, 1));

            //generate goal importance
            agentConfiguration.GoalsState.ForEach(kvp =>
            {
                var goalName = kvp.Key;
                var configuration = kvp.Value;

                var goal = agent.AssignedGoals.FirstOrDefault(g => g.Name == goalName);
                if (goal == null) return;

                double importance = configuration.Importance;

                if (configuration.Randomness)
                {
                    if (string.IsNullOrEmpty(configuration.BasedOn))
                    {
                        var from = (int)(configuration.RandomFrom * 10);
                        var to = (int)(configuration.RandomTo * 10);

                        importance = GenerateImportance(agent, configuration.RandomFrom, configuration.RandomTo);
                    }
                    else
                    {
                        var anotherGoalImportance = agent.InitialGoalStates[agent.AssignedGoals.FirstOrDefault(g => g.Name == configuration.BasedOn)]
                            .Importance;

                        importance = Math.Round(1 - anotherGoalImportance, 2);
                    }
                }
                //todo Review initialization
                GoalState goalState = new GoalState(agent, configuration.Value, goal.FocalValue, importance, 0, 0, null, null);

                agent.InitialGoalStates.Add(goal, goalState);

                agent[string.Format("{0}_Importance", goal.Name)] = importance;
            });

            //initializes initial anticipated influence for each kh and goal assigned to the agent
            agent.AssignedDecisionOptions.ForEach(kh =>
            {
                Dictionary<string, double> source;

                if (kh.AutoGenerated && agent.Archetype.DoNothingAnticipatedInfluence != null)
                {
                    source = agent.Archetype.DoNothingAnticipatedInfluence;
                }
                else
                {
                    agentConfiguration.AnticipatedInfluenceState.TryGetValue(kh.Id, out source);
                }


                Dictionary<Goal, double> inner = new Dictionary<Goal, double>();

                agent.AssignedGoals.ForEach(g =>
                {
                    inner.Add(g, source != null && source.ContainsKey(g.Name) ? source[g.Name] : 0);
                });

                agent.AnticipationInfluence.Add(kh, inner);
            });


            InitializeDynamicVariables(agent);

            agent.AgentStateConfiguration = agentConfiguration;

            return agent;
        }

        private static void InitializeDynamicVariables(Agent agent)
        {
            agent[AlgorithmVariables.IsActive] = true;
        }

        private static double GenerateImportance(Agent agent, double min, double max)
        {
            double rand;

            if (agent.ContainsVariable(AlgorithmVariables.Mean) && agent.ContainsVariable(AlgorithmVariables.StdDev))
                rand = NormalDistributionRandom.GetInstance.Next(agent[AlgorithmVariables.Mean], agent[AlgorithmVariables.StdDev]);
            else
                rand = NormalDistributionRandom.GetInstance.Next();

            rand = Math.Round(rand, 1, MidpointRounding.AwayFromZero);

            if (rand < min || rand > max)
                return GenerateImportance(agent, min, max);

            return rand;
        }
    }
}
